### ISSUE TITLE
Help button doesn't work

### ISSUE THREAD

**Issue by moffeemoffee** [ratsounds/saomddc#1]
You can reproduce it by simply presing the help button.

```
Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLButtonElement.<anonymous> (ui.js:176)
```

**Comment by ratsounds** [comment]
I'm closing all old pull requests and issues due to the new open development system.
Fixed. Thank you for your report

I'm sorry for terribly delayed my action. 
thx.
