### ISSUE TITLE
Pretty print data json files to meaningful diff 

### ISSUE THREAD

**Issue by item4** [ratsounds/saomddc#2]
currently data file was compressed.

It is good for web access, but not good to version control and read.

I think original file will be uncompressed and publish compressed version to GitHub Pages automaticallly by CI.

**Comment by ratsounds** [comment]
I'm closing all old pull requests and issues due to the new open development system.
Fixed. Thank you for your suggestion

I'm sorry for terribly delayed my action. 
thx.
