### ISSUE TITLE
More information ?

### ISSUE THREAD

**Issue by Asgarrrrr** [ratsounds/saomddc#3]
**Hello,**

I would have liked to know if it was possible to obtain more information in the data.json, like the url towards the artwork or the cutin or lore.

Thank you thank you beautiful for all your work @ratsounds !!!

**Comment by ratsounds** [comment]
I'm closing all old pull requests and issues due to the new open development system.

data.json is build from google spreadsheet based script. 
data builder spreadsheet and data description will be published in the future.

I'm sorry for terribly delayed my action. 
thx.
